extends Node

var MAIN_MENU_SCENE_PATH: String = "res://scenes/MainMenu.tscn"
var BASE_GAME_SCENE_PATH: String = "res://scenes/BaseGame.tscn"
var SURVIVAL_GAME_SCENE_PATH: String = "res://scenes/SurviveGame.tscn"

var GAME_MODES: Array = ["Score Attack", "Survival", "Dungeon"]
var BOARD_SIZES: Array = ["Small", "Medium", "Large", "X-Large"]
var DIFFICULTIES: Array = [
	"Beginner",
	"Easy",
	"Intermediate",
	"Moderate",
	"Normal",
	"Challenging",
	"Hard",
	"Very Hard",
	"Expert"
]

var TILE_GAP: int = 30
var BOMB_INDEX: int = 10

var BASE_GAME_MODE_ID: int = 0
var SURVIVAL_GAME_MODE_ID: int = 1
var DUNGEON_GAME_MODE_ID: int = 2
var ALL_GAME_MODE_IDS: Array = [BASE_GAME_MODE_ID, SURVIVAL_GAME_MODE_ID, DUNGEON_GAME_MODE_ID]

var BEGINNER_DIFFICULTY_ID: int = 0
var EASY_DIFFICULTY_ID: int = 1
var INTERMEDIATE_DIFFICULTY_ID: int = 2
var MODERATE_DIFFICULTY_ID: int = 3
var NORMAL_DIFFICULTY_ID: int = 4
var CHALLENGING_DIFFICULTY_ID: int = 5
var HARD_DIFFICULTY_ID: int = 6
var VERY_HARD_DIFFICULTY_ID: int = 7
var EXPERT_DIFFICULTY_ID: int = 8
var ALL_DIFFICULTY_IDS: Array = [
	BEGINNER_DIFFICULTY_ID,
	EASY_DIFFICULTY_ID,
	INTERMEDIATE_DIFFICULTY_ID,
	MODERATE_DIFFICULTY_ID,
	NORMAL_DIFFICULTY_ID,
	CHALLENGING_DIFFICULTY_ID,
	HARD_DIFFICULTY_ID,
	VERY_HARD_DIFFICULTY_ID,
	EXPERT_DIFFICULTY_ID
]

var EASY_GOAL_DIFFICULTIES: Array = [
	BEGINNER_DIFFICULTY_ID,
	MODERATE_DIFFICULTY_ID,
	HARD_DIFFICULTY_ID
]

var NORMAL_GOAL_DIFFICULTIES: Array = [
	EASY_DIFFICULTY_ID,
	NORMAL_DIFFICULTY_ID,
	VERY_HARD_DIFFICULTY_ID
]

var NO_TILE_LOCKING_DIFFICULTIES: Array = [
	BEGINNER_DIFFICULTY_ID,
	EASY_DIFFICULTY_ID,
	INTERMEDIATE_DIFFICULTY_ID
]

var HARD_TILE_LOCKING_DIFFICULTIES: Array = [
	HARD_DIFFICULTY_ID,
	VERY_HARD_DIFFICULTY_ID,
	EXPERT_DIFFICULTY_ID
]

var SMALL_BOARD_SIZE_ID: int = 0
var MEDIUM_BOARD_SIZE_ID: int = 1
var LARGE_BOARD_SIZE_ID: int = 2
var XLARGE_BOARD_SIZE_ID: int = 3
var ALL_BOARD_SIZE_IDS: Array = [
	SMALL_BOARD_SIZE_ID,
	MEDIUM_BOARD_SIZE_ID,
	LARGE_BOARD_SIZE_ID,
	XLARGE_BOARD_SIZE_ID
]
